README.md, command.go, examples/example1.go, examples/example2.go, examples/example3.go, examples/example4.go, examples/example5.go, examples/example6.go, examples/example7.go, response.go, slacker.go
⚠️  Breaking API change suggestion
Replacing the type Response by ResponseWriter lets
users wrap the response type with their own implementation.
Ex: adding logging for all outgoing messages in one central place.
````go
type CustomErrorWriter struct {
slacker.ResponseWriter
}
func (l *CustomErrorWriter) ReportError(err error) {
response := fmt.Sprintf("custom error format: %s", err)
l.ResponseWriter.Reply(response)
}
func CustomError(f func(r *slacker.Request, w slacker.ResponseWriter)) func(r *slacker.Request, w slacker.ResponseWriter) {
fn := func(r *slacker.Request, w slacker.ResponseWriter) {
rw := &CustomErrorWriter{w}
f(r, rw)
}
return fn
}
// Usage
bot.Command("ping", "Ping!", CustomError(func(request *slacker.Request, w slacker.ResponseWriter) {
w.ReportError(errors.New("my …
```
=> Replacing Response by interface ResponseWriter

request.go, slacker.go
Example use:
````go
bot := slacker.New("secret-token", slacker.WithTimeout(5*time.Second))
bot.Command("ping", "Ping!", CustomError(func(request *slacker.Request, response slacker.ResponseWriter) {
rand.Seed(time.Now().UTC().UnixNano())
n := rand.Int63n(10) // wait up to 10 seconds
t := time.After(time.Duration(n) * time.Second)
select {
case <-request.Ctx.Done():
response.ReportError(errors.New("⚠️ Timed out"))
case <-t:
response.Reply(fmt.Sprintf("Waited %d seconds to say: pong!", n))
}
}))
````
I originally wanted to hide the `request.Ctx.Done():` from the command but couldn't find an elegant way to do it.
Let me know what you think.
=> Add context

slacker.go
After the cleanup, _client_ in _slacker_  struct is "_private_". I was using Client to get some info about the user. So I added a method that returns it.
@shomali11 What do you think about it?
=> Add GetUserInfio

command.go, slacker.go
By making BotCommand an interface, we make it easier to mock test it.
Exposing the available commands register in Slacker, allows us to write
our own custom help function having access to the usage and description.
=> Make BotCommand an interface. Have Slacker expose the list of commands.

response.go
Otherwise it will fail and return an error.
@shomali11 This was missing in https://github.com/shomali11/slacker/pull/29
=> Pass the text to PostMessage as a MsgOption

defaults.go, slacker.go
It's useful to see nlopes/slack debug output when debugging connection issues or developing a bot. Added ability to enable such messages via environment variable `SLACKER_DEBUG`.
=> Enable debugging output if envvar SLACKER_DEBUG is set

slacker.go
Changed control flow of slacker.Slacker.Listen() so that it doesn't
prioritize slack channel events > context events
Re: https://github.com/shomali11/slacker/issues/33
Not sure if this is the best way to shut down a slacker bot but that's what I'm using now. Welcome feedback.
Would appreciate comments on error returns- notice inline comments
=> context.CancelFunc now propogates immediately

slacker.go
Last one, I promise! Very simple.
**Purpose:**
Exposing _nlopes/slack_ members in the `slacker` structure allows us to create an arbitrary slack bot, and then use "slacker" as a command/control interface for it. E.g.: A slack bot that relays important logs in RTM w/o command, but can be fine-tuned by slacker commands.
**Implementation:**
Created Getter func's for said purpose
=> Added getters to Slacker for members

defaults.go, response.go
Extend Reply defaults to include Blocks and include these in the rtm.PostMessage.
Implements #46 
Signed-off-by: Philip Marc Schwartz <Philip.Schwartz1@T-Mobile.com>
=> Add support for Block Kit

go.mod, go.sum
This update adds support for Slack's [rich text update](https://api.slack.com/changelog/2019-09-what-they-see-is-what-you-get-and-more-and-less). The crucial commit here is https://github.com/nlopes/slack/commit/c4750fe73d883a2b1edff13e0d2e09290512b405#diff-74e7523bcca0f2b33679f1a95e2c64ad which prevents the UnmarshalJSON from returning an error by skipping over any `rich_text` blocks.
=> Update nlopes/slack dependency

defaults.go, examples/11/example11.go, response.go, slacker.go
As the timestamp is needed to reply in thread, made some changes to be able to have this optional methods in `ResponseWriter`
- Changed `ResponseWriter` interface to have replies methods with `InThread` version
- Changed contructor to receive the events instead of only the channel
- Adapted the whole code to comply to the new interface and constructor
=> Enabling reply in thread

examples/11/example11.go, response.go
Posting messages to Slack can fail due to a variety of reason. For example, exceeding the maximum number of characters in a message. Currently, the `ResponseWriter` does not return any error that may have occurred using the `Reply` method. Because of this, it's possible that messages could not be sent and you may not notice.
This changes the `ResponseWriter` interface to return an `error` in the `Reply` method.
This change should not break usages of `rw.Reply` as it did not return anything before, but it is a breaking change because custom `ResponseWriter`s have to return an error now on reply.
Let me know if you think we should not be breaking the API to think of another possible solution.
Thank you!
=> propagate errors when posting a message

response.go
Whenever a message is posted on the thread, the bot replies in the channel instead of the thread. The `EventTimestamp` value was used for the param `ThreadTimestamp` to post a thread reply which was causing the original issue. Changing this to `event.ThreadTimestamp` fixed the thread replies.
=> Fix the thread timestamp

README.md
Adds information on preparing a Slack app for Socket Mode connections, enough to get the examples working.
Relates to #72
=> README: Add section on preparing your Slack App

README.md, examples/app_manifest/manifest.yml
This adds a simple app manifest that should work for all the examples, and updates the documentation to mention this app manifest.
It also expands on the manual steps to setup the app to include some recommended scopes for getting started, and adds a troubleshooting section to identify some common issues that cause a bot to not respond to events properly.
=> Documentation Improvements, Simple App Manifest

slacker.go
Currently the `func (s *Slacker) Listen(ctx context.Context) error`  accepts a context but it is only used by the inner goroutine to stop the select loop.
When the context is cancelled, the inner goroutine stops but not the socketmode client.
Since the socketmode client has a `RunContext` method, using it will allow graceful shutdowns.
=> Socket mode client with context

README.md, examples/app_manifest/manifest.yml
The manifest we ship sets up both message.im and message.channel in
addition to app_mention, but if app_mention is included with either
message event types then in the case where an app_mention is in a dm
(message.im) or channel (message.channel) that the bot is in, the bot
will receive two events and respond twice (as was seen in #82).
While a user may want that for some reason, they would also need to
account for that in their command code. To be friendlier for users
attempting to get started, we'll remove the app_mention since message.im
and message.channel will send an event whether the bot is mentioned or
not as long as it is in the channel.
=> Remove app_mentions from manifest

command.go, context.go, examples/18/example18.go, slacker.go
Add support for slash commands within CommandDefinition.
Add support for interactive events as part of the CommandDefinition.
```golang
func wasArticleUseFulCmd(actionId string) func(botCtx slacker.BotContext, request slacker.Request, response slacker.ResponseWriter) {
return func(botCtx slacker.BotContext, request slacker.Request, response slacker.ResponseWriter) {
....
}
}
func wasArticleUseFulInteractive(s *slacker.Slacker, e *socketmode.Event, callback *slack.InteractionCallback, request *socketmode.Request) {
...
}
func main() {
bot := slacker.NewClient(....)
bot.Command("was-this-article-useful", &slacker.CommandDefinition{
BlockID:     "was_article_useful",
Handler:     wasArticleUseFulCmd("was_article_useful"),
Interactive: wasArticleUseFulInteractive,
})
}
```
=> Add support for slash commands and interactive msg

README.md
Introduced {word} vs <sentence> parameter matching
This is from a new version from an underlying library `commander`
=> word vs sentence

README.md, examples/13/example13.go, slacker.go
This feature will allow users to define a custom default inner event handler, such as handlers for events like:
- member_joined_channel
- member_left_channel
- group_left
- group_deleted
etc...
This would make the world of difference for some tooling we're building that we're hoping to use Slacker for
https://github.com/shomali11/slacker/issues/112
=> Add ability to define a default inner event handler

go.mod, go.sum, slacker.go
Updated slack-go to latest available, fix getChannelName after slack-go update.
=> Update slack-go to latest available, fix getChannelName

message_event.go, response.go, slacker.go
Using the `log` package ensures that timestamps are emitted with our log entries, and the format matches the logging behavior of the slack-go library when debugging is enabled.
Certain log entries, such as ignoring unsupported events, are now gated by whether or not debugging has been enabled.
Closes #131
=> fix: Use log package for logging

.git-czrc.json, .github/workflows/commit-message-check.yaml, CONTRIBUTING.md, MAINTAINING.md
- Updates contributor docs to include details about our commit message convention
- Adds a GitHub workflow to ensure commit messages follow our convention.
- Updates maintainer docs to include information about how we release new versions.
Closes #129, closes #130
=> Project maintenance updates

.github/workflows/commit-message-check.yaml
While we keep merge commits, we need to account for them in our message check. GoReleaser seems to ignore them so this doesn't impact the changelog.
=> chore: Fix commit message check

message_event.go
In commit d3d36ce8fb8cf7a9110034b02acf671ad6a37146 a regression was introduced that broke BotInteractionMode and instead ignored all bot messages.
Closes #135
=> fix: Resolve regression of BotInteractionMode

defaults.go, slacker.go
This PR adds `WithAPIURL` as a `ClientOption` when constructing the client. This allows one to set the URL to the Slack API. While this is not necessary for real-life connections, allowing this override permits unit testing with `httptest` and the testing frameworks in <https://github.com/slack-go/slack/tree/master/slacktest>.
I refactored the initialization in `slacker.go` a bit so that we only actually set the option on the Slack client if we've defined a URL. I could have hard-coded the Slack API URL as a default and that would probably work great as well. However, I didn't want to make any changes (even under the hood) for the vast majority of users that won't call this option, and implementing it this way makes this change a no-op for everyone else.
=> Add Client config option to let the slack API URL be set

.goreleaser.yaml
archives.replacements was deprecated 2022-11-24 and expired recently on 2023-06-06, causing our builds to break.
=> chore: Address goreleaser config deprecations

examples/interaction-middleware/main.go, examples/interaction-shortcut/main.go, examples/interaction-view/main.go, examples/interaction/main.go, interaction.go, slacker.go
Convert BlockID to InteractionID field into the InteractionDefinition struct,
and add the necessary dispatch mechanisms to handle the following interactions:
- shortcut
- message_actions
- view_submission
- view_closed
=> feat: Handle more interaction types
